version: '3.9'
services:
  draft-front:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - port=3000
      # - CHOKIDAR_USEPOLLING=true
    tty: true
    working_dir: /app
    entrypoint: yarn dev -o